name: Test Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint --if-present

      - name: Build MCP server
        run: npm run build:mcp

      - name: Verify build output
        run: |
          test -f dist/mcp/server.js || exit 1
          test -f bin/axionsjs-mcp.js || exit 1
          echo "Build verification successful"

      - name: Test package structure
        run: npm pack --dry-run

      - name: Test binary execution
        run: |
          timeout 5s node bin/axionsjs-mcp.js || true
          echo "Binary test completed"
